{% set version = "20230430" %}

package:
  name: diff-match-patch
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diff-match-patch/diff-match-patch-{{ version }}.tar.gz
  sha256: 953019cdb9c9d2c9e47b5b12bcff3cf4746fc4598eb406076fa1fc27e6a1f15c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=38.6.0
    - flit
  run:
    - python

test:
  imports:
    - diff_match_patch

about:
  home: http://code.google.com/p/google-diff-match-patch/
  license: Apache-2.0
  license_file: LICENSE
  summary: Diff Match Patch is a high-performance library in multiple languages that manipulates plain text

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
