{% set version = "20241021" %}

package:
  name: diff-match-patch
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diff-match-patch/diff_match_patch-{{ version }}.tar.gz
  sha256: beae57a99fa48084532935ee2968b8661db861862ec82c6f21f4acdd6d835073

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
  run:
    - python >=3.7

test:
  imports:
    - diff_match_patch

about:
  home: http://code.google.com/p/google-diff-match-patch/
  license: Apache-2.0
  license_file: LICENSE
  summary: Diff Match Patch is a high-performance library in multiple languages that manipulates plain text

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
